### ISSUE TITLE
Image trace is not shown

### ISSUE THREAD

**Issue by a2ckr** [JuliaPluto/PlutoPlotly.jl#16]
Image trace does not display well. 

```julia
using PlutoPlotly
plot(image(;z = rand(3,5,3)*255))
```

The error message is as follows

<img width="746" alt="Screen Shot 2023-06-22 at 21 16 54" src="https://github.com/JuliaPluto/PlutoPlotly.jl/assets/43717589/41d0dbce-2a09-4eab-9799-345045653fd8">

The workaround is to use `Plot()` with a capital P.

[PlutoPlotly : Image trace is not shown \- General Usage \- Julia Programming Language](https://discourse.julialang.org/t/plutoplotly-image-trace-is-not-shown/100699/1)

---

Pluto.jl(v0.19.26), PlutoPlotly.jl(v0.3.7) 
```
julia> versioninfo()
Julia Version 1.8.1
Commit afb6c60d69a (2022-09-06 15:09 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin21.4.0)
  CPU: 16 × Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 6 on 16 virtual cores
Environment:
  JULIA_NUM_THREADS = 6
  DYLD_LIBRARY_PATH = /usr/local/opt/suite-sparse/lib:
```

**Comment by disberd** [comment]
This should now be fixed with #17
