### ISSUE TITLE
Can not make subplots

### ISSUE THREAD

**Issue by KronosTheLate** [JuliaPluto/PlutoPlotly.jl#29]
In https://github.com/JuliaPluto/PlutoPlotly.jl/blob/main/notebooks/make_subplots_tests.jl the examples use a function `make_subplots`. This function is not available in the latest version of PlutoPlotly.

Also, the examples from http://juliaplots.org/PlotlyJS.jl/stable/manipulating_plots/#Subplots produce a vector, instead of a concatinated single plot. This vector has to be folded out after each evalution, so that does not work. Making `hcat`, `vcat`\ and `hvcat` work the same on `PlutoPlot` as `Plot` would be ideal.

I guess I am left with the option of using the `Subplots` function, but it is not really documented.

**Comment by KronosTheLate** [comment]
This works very well:
```julia
vcat(p1.Plot, p2.Plot)|>PlutoPlot
```
I guess we just need some internal plumbing to specialize on PlutoPlot as well.

**Comment by disberd** [comment]
The forward of all relevant PlotlyBase methods to the Plot object has been merged with #23, but I did not release a new version yet on the general registry as I am waiting for some other tweaks

**Comment by disberd** [comment]
In the end I decided to publish the current status as v0.4.0 and the do another breaking change when I finish implementing the refactor.
Given that https://github.com/JuliaRegistries/General/pull/92837 has been merged this is now doable with the latest version so I close this

**Comment by disberd** [comment]
Actually reopening this as the new version does work with the `make_subplots` but with `hcat` or `vcat` probably due to #25.

**Comment by disberd** [comment]
It should now be fixed with #30 in v0.4.1
