### ISSUE TITLE
Heatmap behavior 

### ISSUE THREAD

**Issue by dorn-gerhard** [JuliaPluto/PlutoPlotly.jl#3]
I just figured out that the decision who is the x axis and who the y axis has a different behavior in 
PlotlyLight and PlutoPlotly:

![image](https://user-images.githubusercontent.com/67096719/162992902-ac06cf42-8424-4c05-9669-f45d25c6cf45.png)

Further observation: transposing the ``zz`` variable ``zz'`` leads to an error in PlutoPlotly. (maybe a collect is needed).
permutedims works.

**Comment by disberd** [comment]
Thanks for the report @dorn-gerhard and thanks for the suggestion @empet!
I think the problem here is indeed the skipping of JSON serialization to use `publish_to_js` for speed/optimization.

I'll try to have a look on how to fix this to make it consistent with the expected behavior!
