### ISSUE TITLE
How to incorporate plots! and then use PlutoPlotly for click events

### ISSUE THREAD

**Issue by hisacro** [JuliaPluto/PlutoPlotly.jl#37]
hello I asked for an help in julia discourse, but it was about backend. Now that this PlutoPlotly is in maturing stage, I want to know is this possible? 

plotting multiple implicit functions and getting the coordinates on click event.

https://discourse.julialang.org/t/need-a-simple-backend-for-plots-inside-pluto-that-support-click-event-when-plotting-implicit-equations/107862/1

I have included a sample code too, Any help or pointers are much appreciated. Sorry for cross posting but I will make to sure to update solution everywhere if I find one

**Comment by disberd** [comment]
Hi @hisacro,

I directly replied on the discourse thread but while what you want to achieve it's possible it is not very polished and still requires non-trivial manual tweaking.

As I gave a full working example and a small video sample in the discourse thread that you linked I will not repeat this here.

Closing this as this is not a PlutoPlotly issue per se.
