### ISSUE TITLE
How to access plotlyjs()

### ISSUE THREAD

**Issue by kichappa** [JuliaPluto/PlutoPlotly.jl#38]
I was trying to change the height of the plot window inside pluto, but I reached nowhere. However, I saw that I can use `plotlyjs(size = (700, 400))` to do it in PlotlyJS.jl. 

How can I access this function through PlutoPlotly? Or better, how can I change the size of the plotting window, increase the red arrow length?
![image](https://github.com/JuliaPluto/PlutoPlotly.jl/assets/10088817/19102eed-702f-41f7-b283-057810d69aea)

**Comment by disberd** [comment]
I can not find a `plotlyjs` function in the PlotlyJS package, are you sure @kichappa that you are not using Plots.jl with the `plotlyjs` backend?

In PlutoPlotly as well as in vanilla PlotlyJS you control the size (width and height) of the plot with the `width` and `height` keyword arguments that you pass to the [Layout](https://juliaplots.org/PlotlyJS.jl/stable/building_traces_layouts/#Layouts) object you pass as second argument to the `plot` function.

So for example:
```julia
plot(scatter(;y = rand(10)), Layout(;height = 600))
``` 
![image](https://github.com/JuliaPluto/PlutoPlotly.jl/assets/12846528/d7fc3489-aa22-4b39-94f7-0a2bc36263cd)

**Comment by disberd** [comment]
Closing as this is not PlutoPlotly related and no further feedback was given by @kichappa to the proposed solution
