### ISSUE TITLE
Avoid inserting files into Pluto's frontend-dist folder

### ISSUE THREAD

**Issue by fonsp** [JuliaPluto/PlutoPlotly.jl#39]
Let's figure out together how we can avoid inserting files into the `frontend-dist` folder of Pluto. This hack seems to work quite well, but my worries are:
- This creates inflexibility in future development. If you stick to the known and documented API, then we are flexible to change things internally without breaking packages that use API. 
- Or for example, if VS Code were to support some of our special display API, then we want PlutoPlotly.jl to work. Also within the Pluto ecosystem, we display notebooks in lots of environments, like locally, from a remote server, from a CDN, from the future pluto.land, with [inlined assets](https://github.com/fonsp/Pluto.jl/pull/2802), and those things become harder to develop.
- PlutoPlotly.jl should give an example to other Pluto-integrating packages on how to do these things :)
- Dogfooding: if there are missing Pluto features, we should add them instead of working around it.

**Comment by disberd** [comment]
Yeah I'd be more than happy to have an official way to do this with Pluto API.

I didn't even publicize this as it was more experimenting on how to get offline plotly easily (though there should still be a fallback to cdn if this fails so it won't break plots in the general sense) and I always wanted to find a more proper approach so let's discuss this :D. 

As I mentioned some time ago I don't think the approach in your example notebook about importing local js is feasible as it will send the full library as String at least during manual rerun, and this being a few Mb it gives quite a bit of lag (almost 1 second on my pc)

**Comment by fonsp** [comment]
Here is a notebook that demonstrates the mechanism that we could use:

https://github.com/fonsp/disorganised-mess/blob/main/importing%20local%20JS%20modules%202.jl
