### ISSUE TITLE
Pluto.Plotly: title_text does not work in v0.6

### ISSUE THREAD

**Issue by VivaldoMendes** [JuliaPluto/PlutoPlotly.jl#58]
Hi @disberd,

I just upgraded PlutoPlotly to version 0.6.0, and suddenly, the `title_text` keyword no longer works. Please see the example below. Do you advise me to downgrade the version to 0.5.0 in Pluto, or should I wait for v0.6 to be fixed? Thanks. 

Vivaldo

![a](https://github.com/user-attachments/assets/fe0114db-b42d-4fc4-96fb-a3bac4158fb0)

**Comment by disberd** [comment]
Hi @VivaldoMendes, sorry to hear that.
I'll have a look in the morning and try to fix that

**Comment by VivaldoMendes** [comment]
Hi @disberd,

Thank you so much for the speedy fixing. Now, it is working without any problem. Thanks.
