### ISSUE TITLE
Warning in custom sysimage

### ISSUE THREAD

**Issue by jbrea** [JuliaPluto/PlutoPlotly.jl#9]
When backing PlutoPlotly into a custom sysimage that contains Pluto and PlutoPlotly, I get the following warning upon starting Pluto
```julia
┌ Warning: You loaded this package outside of Pluto, this is not the intended behavior and you should use either PlotlyBase or PlotlyJS directly
└ @ PlutoPlotly ~/.julia/packages/PlutoPlotly/8WjBh/src/PlutoPlotly.jl:12
```
Does `is_inside_pluto()` not work as intended in this case?

Steps to reproduce on julia 1.7.3
```julia
using Pkg
Pkg.activate(temp = true)
Pkg.develop("PrecompilePlutoCourse")
cd(joinpath(Pkg.devdir(), "PrecompilePlutoCourse", "Demo"))
Pkg.activate(".")
using Demo
Demo.create_sysimage()
Demo.start()
```

**Comment by disberd** [comment]
I think this happens because when you are precompiling during creation of the sysimage the code is ran outside of Pluto and you get the warning.
Did you try to see if the precompiled image actually fails to create plots in Pluto?

**Comment by jbrea** [comment]
The precompiled image works fine and creates plots in Pluto. It's just the warning that looks puzzling :)

**Comment by disberd** [comment]
I'll probably have to reword the warning to mention this can also happen during precompilaton for the sysimage

**Comment by disberd** [comment]
I realized the printing was actually removed in https://github.com/JuliaPluto/PlutoPlotly.jl/commit/b792f2725676218f18f458dbfd772549df5854bc before v0.3.0.
Where you using the latest PlutoPlotly version?
